src/TrackManager/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views
from . import dt
from . import api
from . import file_handlers

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              [
                  #  Pages
                  url(r'^info/$', views.info, name='info'),
                  url(r'^maps/$', views.maps, name='maps'),
                  url(r'^ymaps/$', views.ymaps, name='ymaps'),
                  url(r'^manager/$', views.tasks, name='manager'),
                  url(r'^dispatcher/$', views.dispatcher, name='dispatcher'),
                  url(r'^manager-calc/$', views.manager_calc, name='manager_calc'),
                  url(r'^salary/$', views.salary, name='salary'),
                  url(r'^schedule/$', views.schedule, name='schedule'),
                  url(r'^app_report/$', views.app_report, name='app_report'),
                  url(r'^acts/$', views.acts, name='acts'),
                  url(r'^reports/$', views.reports_page, name='reports_page'),
                  url(r'^payments/$', views.payments, name='payments'),
                  url(r'^deny/$', views.deny, name='deny'),
                  url(r'^tariff_check/$', views.tariff_check, name='tariff_check'),
                  url(r'^client-price/$', views.client_price, name='client-price'),
                  url(r'^driver-price/$', views.driver_price, name='driver-price'),
                  url(r'get_history/$', views.hist, name='hist'),
                  url(r'get_driver_actions/$', views.driver_actions_modal, name='get_driver_actions'),

                  # Order API
                  url(r'change_status/$', api.change_status, name='change_status'),
                  url(r'save_order/$', api.save_order, name='save_order'),
                  url(r'save_order_template/$', api.save_order_template, name='save_order_template'),
                  url(r'load_order_from_template/$', api.load_order_from_template, name='load_order_from_template'),
                  url(r'save_work/$', api.save_work, name='save_work'),
                  url(r'save_job/$', api.save_job, name='save_job'),
                  url(r'save_order_data/$', api.save_order_data, name='save_order_data'),
                  url(r'save_order_doc/$', api.save_order_doc, name='save_order_doc'),
                  url(r'delete_order_doc/$', api.delete_order_doc, name='delete_order_doc'),
                  url(r'check_tariff/$', api.check_tariff, name='check_tariff'),
                  url(r'calc_tariff_form/$', api.calc_tariff_form, name='calc_tariff_form'),
                  url(r'update_payments_report/$', api.update_payments_report, name='update_payments_report'),
                  url(r'get_all_orders/$', api.get_all_orders, name='get_all_orders'),
                  url(r'send_act/$', api.send_acts, name='send_acts'),
                  url(r'del_act/$', api.del_act, name='del_act'),
                  url(r'check_salary/$', api.check_salary, name='check_salary'),

                  # Download attachments
                  url(r'download/(?P<path>.*)$', api.download_doc),

                  # Report files
                  url(r'get_report/$', file_handlers.excel, name='excel'),
                  url(r'report_disp/$', file_handlers.excel, name='disp_excel'),
                  url(r'report_sal/$', file_handlers.report_sal, name='report_sal'),
                  url(r'report_total_drivers/$', file_handlers.report_total_drivers, name='report_total_drivers'),
                  url(r'containers_all/$', file_handlers.containers_all, name='containers_all'),
                  url(r'tn$', file_handlers.transport_invoice, name='tn'),
                  url(r'pl', file_handlers.road_list, name='pl'),
                  url(r'get_act_report$', file_handlers.get_act_report, name='get_act_report'),
                  url(r'act_to_excel$', file_handlers.act_to_excel, name='act_to_excel'),
                  url(r'payments_to_excel$', file_handlers.payments_to_excel, name='payments_to_excel'),
                  url(r'all_payment_to_excel$', file_handlers.all_payments_to_excel, name='all_payments_to_excel$'),
                  url(r'download-driver-price/$', file_handlers.download_driver_price, name='download-driver-price'),
                  url(r'download-client-price/$', file_handlers.download_client_price, name='download-client-price'),

                  # Data tables
                  url(r'get_manager_table/$', dt.ManagerOrderListJson.as_view(), name='manager_list_json'),
                  url(r'get_manager_calc_table/$', dt.OrdersCalc.as_view(), name='orders_calc'),
                  url(r'get_dispatcher_table/$', dt.DispatcherOrderListJson.as_view(), name='dispatcher_list_json'),
                  url(r'get_experiment/$', dt.OrdersExperimental.as_view(), name='dispatcher_experimental'),
                  url(r'get_salary_table/$', dt.SalaryReport.as_view(), name='salaryreport'),
                  url(r'get_acts_table/$', dt.ActReport.as_view(), name='actreport'),
                  url(r'get_payments_table/$', dt.PaymentsReportTable.as_view(), name='get_payments_table'),

                  url(r'get_reports_table/$', dt.get_reports_table, name='get_reports_table'),
                  url(r'get_clients_table/$', dt.get_clients_table, name='get_clients_table'),
                  url(r'get_schedule_table/$', dt.schedule_table, name='s_table'),
                  url(r'get_app_report_table/$', dt.app_report_table, name='app_report_table'),
              ]

src/tms/urls.py
import os
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from TrackManager.views import landing, landing_search

# handler404 = 'TrackManager.views.not_found'
# handler500 = 'TrackManager.views.internal_error'

APP_NAME = os.environ.get('APP_NAME', 'tms')

urlpatterns = [
                  url(r'^ctrack/', include('TrackManager.urls2')),
                  url(r'^' + APP_NAME + '/auth/', include('django.contrib.auth.urls')),
                  url(r'^' + APP_NAME + '/admin/', admin.site.urls),
                  url(r'^' + APP_NAME + '/', include('TrackManager.urls')),
                  url(r'^$', landing, name='landing'),
                  url(r'^search/$', landing_search, name='landing_search')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/TrackManager/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models import F
from django.db.models import PROTECT
from django.utils import timezone
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.exceptions import ValidationError

import datetime
import logging
import os
from . import constants as choices
from .push_service.messaging import send as send_push

log = logging.getLogger('tms')

TIME_ZONE = timezone.get_current_timezone()


def tz_now():
    return timezone.localtime(timezone.now())


class Client(models.Model):
    """Справочник контрагентов
        ContractName- Наименование
        ContractNumber - Номер договора
        ContractDate - Дата договора
        INN - ИНН
        KPP - КПП
        LegalAdress - Юр. адрес
        BankAccount - Банковские реквизиты
        ShortName - Короткое имя для удобства ввода
    """
    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        result = self.shortname if self.shortname else self.Name
        return result

    def __unicode__(self):
        return self.Name

    Name = models.CharField(max_length=100)
    ContractNumber = models.CharField(max_length=100)
    ContractDate = models.DateField()
    INN = models.BigIntegerField()
    KPP = models.IntegerField()
    LegalAdress = models.CharField(max_length=300)
    BankAccount = models.CharField(max_length=300)
    shortname = models.CharField(max_length=80, blank=True, null=True)
    email = models.CharField(max_length=80, blank=True, null=True)
    agent = models.CharField(max_length=100, blank=True, null=True, default='ООО "АВТО ВЛ"')
    # agent = models.ForeignKey('Agent', null=True, blank=True)
    status = models.CharField(
        max_length=1,
        choices=choices.CLIENT_STATUS,
        default='A')


class Driver(models.Model):
    """Справочник водителей
        FIO - ФИО водителя
        PassportData - Паспортные данные
        Phone - телефон
        DrivenLesson - Вод. Удостоверение
        DriverType - Признак [O - Наш, F - Получастник, P - Частник ]
    """
    objects = models.Manager()

    FIO = models.CharField(max_length=100)
    PassportData = models.CharField(max_length=100)
    Phone = models.CharField(max_length=100)
    DrivenLesson = models.CharField(max_length=100)
    DriverType = models.CharField(
        max_length=10,
        choices=choices.DRIVER_TYPE_CHOICES,
        default='O')

    Status = models.CharField(
        max_length=1,
        choices=choices.DRIVER_STATUS,
        default='A')

    dz = models.ForeignKey('DispZone', blank=True, null=True,
                           verbose_name='Зона диспетчеризации', default=1, on_delete=PROTECT)
    app_token = models.CharField(max_length=1000, blank=True, null=True, verbose_name='ID телефона')
    app_version = models.CharField(max_length=100, blank=True, null=True, verbose_name='Версия приложения')

    class Meta:
        verbose_name_plural = 'Водители'

    def __str__(self):
        return " ".join(self.FIO.split(' ')[:-1])


class Customers(models.Model):
    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'Грузополучатели'

    name = models.CharField(max_length=300, verbose_name='Наименование')

    def __str__(self):
        return self.name


class Order(models.Model):
    """ Основная таблица фактов"""
    objects = models.Manager()

    class Meta:
        """Define custom permission to show alailable menu item
        format of name custom_view_"view_name"
        """
        permissions = (
            ("manager", "Ввод заявки"),
            ("dispatcher", "Обработка заявки"),
            ("tariff_check", "Калькулятор"),
            ("manager_calc", "Справка"),
            ("payments", "Ведомость"),
            ("maps", "Отслеживание"),
            ("salary", "Табель"),
            ("schedule", "Работа машин"),
            ("acts", "Акты"),
            ("reports_page", "Отчеты"),
            ("client-price", "Прайсы"),
        )
        verbose_name_plural = 'Заявки'

    # system fields
    Number = models.CharField(max_length=6, blank=False, null=False, verbose_name='Номер')
    CreateDate = models.DateTimeField(auto_now_add=True, blank=False, null=False, verbose_name='Дата создания')
    Manager = models.ForeignKey(User, blank=False, null=False, verbose_name='Менеджер', on_delete=PROTECT)
    Status = models.IntegerField(default=1, choices=choices.STATUS_CHOICES, verbose_name='Статус')

    # order fields
    ExportDate = models.DateTimeField(default=datetime.date.today, verbose_name='Дата подачи')
    ExportTime = models.TimeField(default=datetime.datetime(2017, 1, 1, 0, 0), verbose_name='Время подачи')
    Client = models.ForeignKey(Client, blank=False, null=False, verbose_name='Клиент', on_delete=PROTECT)
    Customer = models.CharField(max_length=300, blank=True, null=True, verbose_name='Заказчик')
    customer_new = models.ForeignKey(Customers, blank=True, null=True, verbose_name='Грузополучатель',
                                     on_delete=PROTECT)
    Proxy = models.CharField(max_length=300, blank=True, null=True, verbose_name='Доверенность')
    ContainerNum = models.CharField(max_length=300, blank=True, null=True, verbose_name='№ контейнера')
    Foot = models.IntegerField(blank=True, null=True, choices=choices.FOOT_CHOICES, verbose_name='Фут')
    Weight = models.FloatField(default=1, blank=True, null=True, verbose_name='Вес')
    CargoName = models.CharField(max_length=300, blank=True, null=True, verbose_name='Наим.груза')
    Operation = models.IntegerField(default=1, choices=choices.OPERATION_CHOICES, verbose_name='Операция')
    Address = models.CharField(max_length=300, blank=True, null=True, verbose_name='Адрес')
    District = models.CharField(max_length=300, blank=True, null=True, verbose_name='Район')
    TerminalLoad = models.ForeignKey('Terminal', blank=True, null=True, related_name="TerminalLoad",
                                     verbose_name='Забор', on_delete=PROTECT)
    TerminalDeliver = models.ForeignKey('Terminal', blank=True, null=True, related_name="TerminalDeliver",
                                        verbose_name='Сдача', on_delete=PROTECT)
    AddressLoad = models.CharField(max_length=300, blank=True, verbose_name='Адрес забора')
    AddressDeliver = models.CharField(max_length=300, blank=True, verbose_name='Адрес сдачи')
    RaywayCr = models.CharField(max_length=300, blank=True, verbose_name='Переезд1')
    RaywayCrDistrict = models.CharField(max_length=100, blank=True, verbose_name='Район Переезда1')
    RaywayCr2 = models.CharField(max_length=300, blank=True, verbose_name='Переезд2')
    RaywayCr2District = models.CharField(max_length=100, blank=True, verbose_name='Район Переезда2')
    Responsible = models.CharField(max_length=300, blank=True, verbose_name='Отвественный')
    Comment = models.CharField(max_length=300, blank=True, null=True, verbose_name='Примечание')
    truck = models.ForeignKey('Truck', blank=True, null=True, verbose_name='Машина', on_delete=PROTECT)
    trailer = models.ForeignKey('Trailer', blank=True, null=True, verbose_name='Прицеп', on_delete=PROTECT)
    driver = models.ForeignKey(Driver, blank=True, null=True, verbose_name='Водитель', on_delete=PROTECT)

    # Зона диспетчеризации
    dz = models.ForeignKey('DispZone', blank=True, null=True, verbose_name='Зона диспетчеризации', on_delete=PROTECT)
    # workflow fields
    # Дата/время передачи заявки диспетчеру
    dispatch_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата передачи диспетчеру')
    # Дата/время согласования заявки диспетчером
    approve_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования')
    # диспетчер согласовавший
    dispatcher_approve = models.ForeignKey(User, blank=True, null=True, related_name="dispatcher_approve",
                                           verbose_name='диспетчер', on_delete=PROTECT)
    # Дата/время отмены согласования заявки диспетчером
    unapprove_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены согласования')
    # Причина отмены согласования заявки диспетчером
    unapprove_reason = models.CharField(max_length=300, blank=True, verbose_name='Причина отмены согл-я')
    # диспетчер отменивший согласование
    dispatcher_unapprove = models.ForeignKey(User, blank=True, null=True, related_name="dispatcher_unapprove",
                                             verbose_name='диспетчер не согл.', on_delete=PROTECT)
    # Дата/время корректировки заявки
    correction_date = models.DateTimeField(blank=True, null=True, verbose_name='Время корректировки')
    # Дата/время отмены заявки менеджером
    cancel_date = models.DateTimeField(blank=True, null=True, verbose_name='Время отмены менеджером')
    # Причина отмены заявки менеджером
    cancel_reason = models.CharField(max_length=300, blank=True, verbose_name='Причина отмены')
    # Дата/время отклонения заявки диспетчером
    decline_date = models.DateTimeField(blank=True, null=True, verbose_name='время отклонения диспетчером')
    # Причина отклонения заявки диспетчером
    decline_reason = models.CharField(max_length=300, blank=True, verbose_name='Причина отклонения')
    # диспетчер отклонивший заявку
    dispatcher_decline = models.ForeignKey(User, blank=True, null=True, related_name="dispatcher_decline",
                                           verbose_name='отклонивший диспетчер', on_delete=PROTECT)
    # Дата/время назначения авто
    assign_date = models.DateTimeField(blank=True, null=True, verbose_name='время назначения')
    # диспетчер назначивший авто
    dispatcher_assign = models.ForeignKey(User, blank=True, null=True, related_name="dispatcher_assign",
                                          verbose_name='диспетчер назначивший', on_delete=PROTECT)

src/TrackManager/templates/TrackManager/acts.html
{% extends "TrackManager/layout.html" %}
{% load cust_tags %}
{% load static %}

{% block title %}Акты{% endblock %}

{% block css %}
<link href="{% static '/tms/css/acts.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container-fluid">

  <div class="page-header">
    <h3>Акты</h3>
  </div>

  <div class="well well-sm">
      <div class="row">
          <div class="col col-md-2">
              <input type="text" class="form-control" id="date_range" title="Период"/>
          </div>
          <!--div class="col col-md-1">
                <a href="{% url 'report_sal' %}" class="btn btn-primary btn-sm" type="button" class="btn btn-primary">В Excel</a>
          </div-->
          <div class="col col-md-2">
            <select id="filter_client" title="Поиск по клиенту" class="form-control input-md">
                {% if clients|length > 1 %}
                    <option value="" selected>Клиент </option>
                {% endif %}        
                {% for c in clients %}
                    <option value="{{ c.id }}">{{ c.Name }}</option>
                {% endfor %}                
            </select>
        </div>
        <div class="col col-md-1">
          <div class="dropdown">
              <button class="btn btn-default dropdown-toggle btn-sm" type="button" id="dropdownMenu1"
                      aria-haspopup="true" aria-expanded="true">
                  Статус
                  <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1"
                  style="padding-left: 10px; padding-bottom: 10px;">

                  {% for b in bill_statuses %}
                      <li class="checkbox"><label>
                          {% if b.0 == 1 %}
                            <input type="checkbox" name="filter_status" value="{{b.0 }}">{{ b.1 }}</label>
                          {% else %}
                            <input type="checkbox" name="filter_status" value="{{b.0 }}" checked>{{ b.1 }} </label>
                          {% endif %}
                      </li>
                  {% endfor %}
                      <button class="btn btn-default btn-sm" type="button" id="filter_status_apply">
                          Применить
                      </button>
                  </li>
              </ul>
          </div>
        </div>
      </div>
  </div>

  <div class="">
    <table class="table table-bordered table-striped table-hover" id="ActTable">
      <thead>
        <tr>          
          <th>#</th>
          <th>Клиент</th>
          <th>Номер</th>          
          <th>Создан</th>          
          <th>Кол-во заявок</th>
          <th>Сумма</th>
          <th>С</th>
          <th>По</th>
          <th>Статус</th>               
          <th>Действие</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>


</div><!-- /.container -->
{% endblock %}

{% block js %}
<script src="{% static '/tms/js/acts.min.js' %}"></script>
{% endblock %}

src/TrackManager/templates/TrackManager/check_tariff.html
{% extends "TrackManager/layout.html" %}
{% load cust_tags %}
{% load static %}
{% block title %}Тарифы{% endblock %}

{% block css %}
<link href="{% static '/tms/css/dispatcher.min.css' %}" rel="stylesheet">
{% endblock %}

{% block nav_dispatcher %} active{% endblock %}

{% block content %}

<div class="container-fluid">

  <div class="page-header">
    <h3>Узнайте стоимость по прайс-листам</h3>
  </div>

<!-- <div class="row">
  <div class="form-group col-xs-2">
    <a href="/tms/get_report" type="button" class="btn btn-info">Рассчи по заявкам </a>
  </div>
</div> -->

<div class="form-group col-xs-2">
    <button data-toggle="modal" data-target="#Request" class="btn btn-info">Калькулятор</button>
  </div>

<div class="modal fade" id="Request" role="dialog" aria-labelledby="RequestModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="RequestModalLabel">Расчет заявки</h4>
            </div>
            <div class="modal-body well bs-component">
                <form id="RequestForm" action="/{{APP_NAME}}/calc_tariff_form/" method="POST">
                    <input type="hidden" name="Status" id="id_Status">
                    <!-- row -->
                    <div class="row">
                        <div class="form-group col-md-4">
                             <label class="control-label" for="id_Client">Клиент</label>
                            <select name="Client" class="form-control" id="id_Client">
                                {% for c in clients %}
                                <option value="{{ c.id }}">{{ c.Name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                             <label class="control-label" for="id_District">Район</label>
                            <select name="District" class="form-control"  id="id_District">
                                {% for d in city_directions %}
                                <option value="{{ d }}">{{ d }}</option>
                                {% endfor %}
                                 <option value="">-------</option>
                                {% for r in region_directions %}
                                <option value="{{ r }}">{{ r }}</option>
                                {% endfor %}
                                <option value="">-------</option>
                                {% for c in country_directions %}
                                <option value="{{ c }}">{{ c }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group col-md-4" {% if is_client %} hidden {% endif %}>
                                <label class="control-label" for="id_driver">Водитель:</label>
                                <select name="driver" class="form-control driver-selector" data-other="#id_driver" id="id_driver">
                                <option value="1" selected="">Наш</option>
                                <option value="73">Частник</option>
                                <option value="75">Получастник</option>
                             </select>
                            </div>
                    </div>
                    <!-- row -->
                    <div class="row">
                        <div class="form-group col-md-4">
                            {{ form.TerminalLoad|label_with_classes:"control-label" }}
                            {{ form.TerminalLoad|input_with_classes:"form-control terminal-selector" }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.TerminalDeliver|label_with_classes:"control-label" }}
                            {{ form.TerminalDeliver|input_with_classes:"form-control terminal-selector" }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.dz|add_classes }}
                        </div>
                    </div>
                    <!-- row -->
                    <div class="row">
                        <div class="form-group col-md-3">
                             <label class="control-label" for="id_RaywayCr">Наличие переезда</label>
                            <select name="RaywayCr" class="form-control"  id="id_RaywayCr">
                                <option value="">Нет</option>
                                <option value="yes">Да</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                             <label class="control-label" for="id_RaywayCrDistrict">Район Переезда</label>
                            <select name="RaywayCrDistrict" class="form-control"  id="id_RaywayCrDistrict">
                                <option value="" selected>-------</option>
                                {% for d in city_directions %}
                                <option value="{{ d }}">{{ d }}</option>
                                {% endfor %}
                                 <option value="">-------</option>
                                {% for r in region_directions %}
                                <option value="{{ r }}">{{ r }}</option>
                                {% endfor %}
                                <option value="">-------</option>
                                {% for c in country_directions %}
                                <option value="{{ c }}">{{ c }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <!-- row -->
                    <div class="row">
                        <div class="form-group col-md-3">
                            {{ form.ExportDate|label_with_classes:"control-label" }}
                            <div class='input-group date' id='datepicker'>
                                {{ form.ExportDate|input_with_classes:"form-control" }}
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                            <input type="hidden" name="ExportTime" value="12:00:00" id="id_ExportTime">
                            <input type="hidden" name="Manager" value="1" id="id_Manager">
                        </div>
                        <div class="form-group col-md-3">
                            {{ form.Operation|add_classes }}
                        </div>
                        <div class="form-group col-md-3">
                            {{ form.Weight|add_classes }}
                        </div>
                        <div class="form-group col-md-3">
                            {{ form.Foot|add_classes }}
                        </div>
                    </div>
                    <!-- row -->
                    <div class="row">
                        <div class="form-group-header">{% if is_client %} Результаты расчета {% else %} Расчет для клиента {% endif %}</div>
                        <div class="form-group col-md-3">
                            {{ form.client_rate|add_classes }}
                        </div>
                        <div class="form-group col-md-3">
                            {{ form.client_transfer|add_classes }}
                        </div>
                        <div class="form-group col-md-3">
                            <label class="control-label" for="id_client_weight_rate">весовой коэффициент</label>
                            <input type="number" name="client_weight_rate" value="0" step="any" class="form-control"
                                   id="id_client_weight_rate">
                        </div>
                        <div class="form-group col-md-3">
                            {{ form.client_total|add_classes }}
                        </div>
                    </div>
                    <div class="row" {% if is_client %} hidden {% endif %}>

                        <div class="form-header">Расчет для водителя</div>
                        <div class="form-group col-md-3">
                            {{ form.salary_rate|add_classes }}
                        </div>
                        <div class="form-group col-md-3">
                            {{ form.salary_transfer|add_classes }}
                        </div>
                        <div class="form-group col-md-3">
                            <label class="control-label" for="id_salary_weight_rate">весовой коэффициент</label>
                            <input type="number" name="salary_weight_rate" value="0" step="any" class="form-control"
                                   id="id_salary_weight_rate">
                        </div>
                        <div class="form-group col-md-3">
                            {{ form.salary_total|add_classes }}
                        </div>
                    </div>
                    <div class="row">
                        <span id="error_message" style="color:red;"></span>
                    </div>

            <div class="modal-footer">
                <a type="button" class="btn btn-default price_link"
                   href="/{{APP_NAME}}/download-client-price?dz_id=1">Прайс Восток</a>
                <a type="button" class="btn btn-default price_link"
                   href="/{{APP_NAME}}/download-client-price?dz_id=2">Прайс Клещиха</a>
                <button type="submit" class="btn btn-primary" > Рассчитать</button>
            </div>
                </form>
            </div>
            
        </div>
    </div>
  </div>

  

  

<!--<form id="check_tariff" action="/tms/check_tariff/" method="POST">-->
    <!--<div class="row">-->
      <!--<div class="form-group col-xs-4">-->
        <!--<input type="text" placeholder="Введите номер заявки" class="form-control" name="number">-->
      <!--</div>-->
      <!--<div class="form-group col-xs-2">-->
        <!--<button type="submit" class="btn btn-success">Рассчитать</button>-->
      <!--</div>-->
      <!--</div>-->
  <!--</form>-->

<!--<div class="row">-->
      <!--<div class="form-group col-xs-4">-->

        <!--<table class="table table-striped">-->
          <!--<tbody>-->

          <!--</tbody>-->
      <!--</table>-->
      <!--</div>-->
    <!--</div>-->
<!--</div>&lt;!&ndash; /.container &ndash;&gt;-->


{% endblock %}

{% block js %}
<script> var client_id = {{ init_client_id }}; </script>
<script src="{% static '/tms/js/tariff_check.min.js' %}"></script>
{% endblock %}

src/TrackManager/templates/TrackManager/deny.html
{% extends "TrackManager/layout.html" %}
{% load cust_tags %}
{% load static %}
{% block title %}Нет доступа{% endblock %}

{% block css %}
<link href="{% static '/tms/css/dispatcher.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container-fluid">
<h5>Нет доступа на данный раздел</h5>
  <div class="page-header">
  </div>
  </div>
{% endblock %}

src/TrackManager/templates/TrackManager/ya_maps.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="https://api-maps.yandex.ru/2.1/?apikey=ваш API-ключ&lang=ru_RU" type="text/javascript">
    </script>
    <script src="{% static '/tms/js/ya_maps.min.js' %}"></script>
</head>

<body>
    <div id="map" style="width: 600px; height: 400px"></div>
</body>

</html>